# Generated by Django 3.0.7 on 2020-06-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('offer', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='')),
                ('per_day_cost', models.FloatField()),
                ('no_of_visits', models.IntegerField()),
                ('type', models.CharField(choices=[('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('safari', 'safari'), ('International', 'International')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
