# Generated by Django 3.0.7 on 2020-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200624_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='subject',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destinations',
            name='type',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Hill Station', 'Hill Station'), ('safari', 'safari'), ('city', 'city'), ('International', 'International')], max_length=100),
        ),
    ]
