# Generated by Django 3.0.7 on 2020-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200625_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Organization', 'Organization'), ('uncategorized', 'uncategorized')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
