# Generated by Django 3.0.7 on 2020-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200628_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='destinations',
            name='type',
            field=models.CharField(choices=[('Beach', 'Beach'), ('HillStation', 'HillStation'), ('safari', 'safari'), ('city', 'city'), ('International', 'International')], max_length=100),
        ),
    ]
