# Generated by Django 3.0.7 on 2020-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200628_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
